on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
    env:
      actor: ${{$GITHUB_ACTOR}}
    steps:
      - uses: actions/checkout@v3
      # - uses: ./.github/actions/issue
      #   id: issue
      #   with:
      #     token: ${{secrets.GITHUB_TOKEN}}
      #     title: "ISSUE Title"
      #     body: "Body Title"
      #     assignees: |
      #       CristinaRibateCog
      # - run: |
      #     echo "Issue: ${{steps.issue.outputs.issue }}"
      - uses: ./.github/actions/hello-docker
        id: hello
        with:
          who-to-greet: "Juan"
      - run: |
          echo "Time: ${{steps.hello.outputs.time }}"
          echo $HELLO
          echo  "${{github.event.pull_request.user.login}}"
          echo  "$GITHUB_ACTOR"
          echo  "$GITHUB_RUN_ID"
          echo  "$GITHUB_REPOSITORY"
          echo  "${{ github.repository }}"
          echo  "$GITHUB_SHA"
          echo  "${{ github.sha }}"
          echo  "${{ github.actor }}"
          echo "$GITHUB_WORKFLOW"
           echo "${{env.actor}}"
          eccho "https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
      # - run: echo ::set-output name=actor::$GITHUB_ACTOR
      #   if: failure()
      #   id: env_variables
      # - name: Create issue
      #   if: failure()
      #   run: |
      #     curl --request POST \
      #     --url https://api.github.com/repos/${{ github.repository }}/issues \
      #     --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
      #     --header 'content-type: application/json' \
      #     --data '{
      #       "title": "Automated issue: ci-push-main fails",
      #       "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.\n\n The commit hash was: _${{ github.sha }}_.",
      #       "labels":["bug"],
      #       "assignees": ["${{ env.actor }}"],
      #       }' \
      #     --fail

      - uses: ./.github/actions/issue
        if: failure()
        name: Error - Create issue
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          title: "Automated issue: ci-push-main fails"
          body: "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.\n\n The commit hash was: _${{ github.sha }}_."
          assignees: |
            ${{ env.actor }}
