on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          title: "ISSUE Title"
          body: "Body Title"
          assignees: |
            CristinaRibateCog
            cristinaribate
      - run: |
          echo "Issue: ${{steps.issue.outputs.issue }}"
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "Juan"
      - run: |
          echo "Time: ${{steps.hello.outputs.time }}"
          echo $HELLO
