name: CI
on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.0"
      - run: npm ci # ~npm install
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v3
        with:
          path: coverage
          name: code-coverage
      - name: Build Project
        if: github.event_name=='push'
        run: npm run build
      - name: Upload Build Folder
        uses: actions/upload-artifact@v3
        if: github.event_name=='push'
        with:
          path: build
          name: build
      - name: ZIP Assets
        if: github.event_name=='push' && github.ref == 'refs/heads/master'
        run: |
          zip -r build.zip ./build
          zip -r coverage.zip ./coverage
      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: github.event_name=='push' && github.ref == 'refs/heads/master'
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
      - name: Create a Release
        if: github.event_name=='push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      - name: pwd
        run: |
          pwd
          ls -a
      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: github.event_name=='push' && github.ref == 'refs/heads/master' # Force to always run this step to ensure "include administrators" is always turned back on
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          owner: CristinaRibateCog
          repo: github-actions-react
          branch: master
      - uses: actions/download-artifact@v3
#      - run: npm install -g surge
#      - name: Deploy to Staging
#        if: github.event_name=="push"
#        run: npx surge --project ./build --domain silent-apparatus.surge.sh
#        env:
#          SURGE_LOGIN: ${{secrets.SURGE_LOGIN }}
#          SURGE_TOKEN: ${{secrets.SURGE_TOKEN }}
